files:
  - { path: $(find-pkg-share whill_sensor_kit_launch)/config/system_diagnostic_monitor/sensor_kit_diag.yaml }

units:
  - path: /autoware/sensing
    type: and
    list:
      - { type: link, link: /autoware/sensing/whill_sensor_kit }

