files:
  - { path: $(find-pkg-share sample_mobile_robot_sensor_launch)/config/system_diagnostic_monitor/sensor_kit_diag.yaml }

units:
  - path: /autoware/sensing
    type: and
    list:
      - { type: link, link: /autoware/sensing/sample_mobile_robot_sensor }

