files:
  - { path: $(find-pkg-share sample_mobile_robot_launch)/config/system_diagnostic_monitor/sample_mobile_robot.yaml }

units:
  - path: /autoware/vehicle
    type: and
    list:
      - { type: link, link: /autoware/vehicle/topic_rate_check/velocity }
      - { type: link, link: /autoware/vehicle/topic_rate_check/steering }
      - { type: link, link: /autoware/vehicle/sample_mobile_robot }

  - path: /autoware/vehicle/topic_rate_check/velocity
    type: diag
    node: topic_state_monitor_vehicle_status_velocity_status
    name: vehicle_topic_status

  - path: /autoware/vehicle/topic_rate_check/steering
    type: diag
    node: topic_state_monitor_vehicle_status_steering_status
    name: vehicle_topic_status
