/**:
  ros__parameters:
    angular_velocity_stddev_xx: 0.00339
    angular_velocity_stddev_yy: 0.00339
    angular_velocity_stddev_zz: 0.00339
    angular_velocity_offset_x: -0.004648
    angular_velocity_offset_y: -0.001
    angular_velocity_offset_z: 0.004
